"""Held-out phrasing pools (stage 0.4d).

The held-out split must measure how well the agent handles requests it has not seen worded before,
so every pool here is written independently of the development pool in the scenario modules.

Rules for every pool (enforced by tests/test_datagen_heldout.py):
- same length as the dev pool, and the same meaning at each index (same placeholders available,
  same difficulty, deadline and ambiguity settings), so labels and edge-case coverage match;
- no text identical to a dev phrasing;
- written by hand, never generated by a model.

Scenarios without an entry cannot yet be generated for the held-out split.
"""
from src.datagen.scenarios.base import Phrasing

HELDOUT: dict[str, list] = {
    # S01 order in transit, within the promised date
    "S01": [
        Phrasing("Order {order_id} for the {product} went in on {placed_date}. Tracking shows it moving "
                 "but there's no arrival date. Any idea when it lands?"),
        Phrasing("Hi, where's my {product} (order {order_id}, placed {placed_date}) at the moment?"),
        Phrasing("My order {order_id} left the warehouse a few days back and the tracking hasn't changed "
                 "since. When is it due?"),
        Phrasing("Please confirm that order {order_id}, the {product}, has been sent and give me an "
                 "estimated arrival."),
        Phrasing("What is the current status of order {order_id}? I'd like an arrival date."),
        Phrasing("The tracking for order {order_id} hasn't updated for two days. Is it still on schedule?"),
    ],
    # S02 late past the promised date
    "S02": [
        Phrasing("You promised order {order_id} by {promised_date}. It isn't here. Where is it?"),
        Phrasing("The {product} from order {order_id} missed its {promised_date} delivery estimate. "
                 "Please check what happened."),
        Phrasing("Delivery date for order {order_id} has gone by and the tracking looks stuck. Can you "
                 "investigate?"),
        Phrasing("According to the site, order {order_id} was due {promised_date}, yet it's still "
                 "marked in transit. Has it been lost?"),
        Phrasing("I bought the {product} on {placed_date}, order {order_id}. It's overdue. When will I "
                 "actually get it?"),
    ],
    # S03 not yet dispatched. Index meaning matches the dev pool:
    # 0-1 plain, 2 deadline too far away, 3 vague urgency, 4 anger without a qualifying trigger.
    "S03": [
        Phrasing("I ordered on {placed_date} (order {order_id}) and no dispatch email has arrived. Has "
                 "it left yet?"),
        Phrasing("Is order {order_id} on its way? All I received was the confirmation message."),
        Phrasing("I'm hoping to have the {product} for a holiday on {deadline_date}. Order {order_id} "
                 "hasn't been sent. When can I expect it to leave?",
                 difficulty="edge", deadline_days=(6, 9)),
        Phrasing("Could you get order {order_id} out quickly? I'd like it sooner rather than later.",
                 difficulty="edge", ambiguity=True),
        Phrasing("I'm irritated that order {order_id} is still sitting there unshipped. When does it go?",
                 tone="frustrated", difficulty="edge"),
    ],
    # S04 order number missing; two open orders
    "S04": [
        Phrasing("Has my order shipped? I haven't had any news."),
        Phrasing("I'd like an update on my parcel but I've lost the order number."),
        Phrasing("Waiting on something I bought and I can't remember the order number. When will it come?"),
        Phrasing("Could you tell me what is happening with my order?"),
        Phrasing("Checking whether my order is on the way."),
        Phrasing("What's the delivery status for what I ordered recently?"),
    ],
    # S22 hard deadline within three days
    "S22": [
        Phrasing("I must have order {order_id} ({product}) by {deadline_weekday} {deadline_date}; it's "
                 "for an occasion. It hasn't left yet. Can it be sped up?",
                 deadline_days=(1, 3), difficulty="edge"),
        Phrasing("Order {order_id} is a present for {deadline_weekday} and the {product} {be} still "
                 "showing as processing. Can it reach me in time?",
                 deadline_days=(1, 3), difficulty="edge"),
        Phrasing("Time-critical: order {order_id} needs to be delivered before {deadline_date} but it "
                 "still says processing.", deadline_days=(1, 3), difficulty="edge"),
        Phrasing("I fly on {deadline_weekday} and need the {product} first. Order {order_id} hasn't "
                 "been sent. What are my options?", deadline_days=(1, 3), difficulty="edge"),
    ],
}