"""Render the baseline report (docs/project/baseline-report.md) from scored results."""
DEFAULT_HOURLY_RATES = (20.0, 30.0, 40.0)    # illustrative assumptions for the sensitivity table, not findings

ACCURACY_ROWS = (
    ("category_ok", "Category correct"),
    ("actions_ok", "Action set exactly correct"),
    ("escalate_ok", "Escalation decision correct"),
    ("consequential_ok", "Consequential actions correct (refund, replacement, exchange, return label, cancellation, address change)"),
    ("kb_ok", "All required knowledge-base articles identified"),
)


def pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def render_report(summary: dict, sample: dict, results: list[dict], hourly_rates=DEFAULT_HOURLY_RATES) -> str:
    t, acc = summary["time"], summary["accuracy"]
    scored = [r for r in results if not r["practice"]]
    first, last = min(r["started_at"] for r in scored)[:10], max(r["started_at"] for r in scored)[:10]
    lines = [
        "# Baseline Report: Manual Ticket Handling", "",
        "Generated by `python -m src.baseline.cli report` from `data/baseline/results.jsonl`. Method: `baseline-protocol.md`.", "",
        "| | |", "|---|---|",
        f"| Dataset | development split, dataset version in `data/manifest.json`, {summary['tickets']} scored tickets |",
        f"| Sample | stratified by scenario, seed {sample['seed']}, {len(sample['practice_ids'])} practice tickets excluded |",
        f"| Handler | one person (the project lead) |",
        f"| Sessions | {first} to {last}; {summary['pauses']} pause(s) recorded |", "",
        "## 1. Handling time", "",
        "Handling time runs from the start of the timer to submission of the reply; paused time is excluded.", "",
        "| Statistic | Seconds | Minutes |", "|---|---|---|",
    ]
    for key, name in (("mean", "Mean"), ("median", "Median"), ("p90", "90th percentile"), ("min", "Fastest"), ("max", "Slowest")):
        lines.append(f"| {name} | {t[key]:.0f} | {t[key] / 60:.1f} |")
    lines += [f"| Total ({t['n']} tickets) | {t['total']:.0f} | {t['total'] / 60:.1f} |", "",
              f"Throughput at the mean: {3600 / t['mean']:.1f} tickets per hour.", "",
              "### By difficulty", "", "| Difficulty | Tickets | Mean seconds | Median seconds | Actions exactly correct |",
              "|---|---|---|---|---|"]
    for difficulty, d in summary["by_difficulty"].items():
        lines.append(f"| {difficulty} | {d['n']} | {d['mean']:.0f} | {d['median']:.0f} | {pct(d['actions_ok'])} |")
    learn = summary["learning"]
    lines += ["", f"### Learning effect", "",
              f"Median time over the first {learn['third']} tickets: {learn['first_third_median']:.0f} s; over the last "
              f"{learn['third']}: {learn['last_third_median']:.0f} s. A large drop would mean early tickets overstate the steady-state time.",
              "", "## 2. Accuracy of manual handling", "", "| Measure | Rate |", "|---|---|"]
    lines += [f"| {label} | {pct(acc[key])} |" for key, label in ACCURACY_ROWS]
    lines += ["", "Tickets where the category or the action set differed from the label:", ""]
    if summary["misses"]:
        lines += ["| Ticket | Scenario |", "|---|---|"] + [f"| {m['ticket_id']} | {m['scenario_id']} |" for m in summary["misses"]]
    else:
        lines.append("None.")
    lines += ["", "## 3. Cost per ticket (sensitivity)", "",
              "Local compute costs nothing, so the business case compares labour time. The hourly rates below are "
              "assumptions chosen to show sensitivity; the rate that applies to a real support team is an input, not a result.", "",
              "| Assumed fully loaded labour cost per hour | Cost per ticket at the mean time | Cost per 1,000 tickets |", "|---|---|---|"]
    lines += [f"| ${r:,.2f} | ${t['mean'] / 3600 * r:,.2f} | ${t['mean'] / 3600 * r * 1000:,.0f} |" for r in hourly_rates]
    lines += ["", "## 4. Limitations", "",
              "- One handler, who is also the author of the project and designed the dataset. Familiarity with the ticket types "
              "probably makes these times faster than a new support agent's, so the baseline may understate real handling time.",
              "- Record lookups run in a terminal tool and are faster than switching between real order, payment and knowledge-base systems.",
              "- Tickets are synthetic and short; real tickets contain more noise, attachments and history.",
              "- Sessions were free of interruptions apart from recorded pauses, unlike a live queue.",
              f"- {summary['tickets']} tickets is a small sample: use the median and the spread, and do not read differences of a few percent as real.",
              "- Accuracy is measured against generated labels, which follow the project's own policy and priority rubric.", ""]
    return "\n".join(lines)
