"""Render the baseline report (docs/project/baseline-report.md) from scored results."""
from src.baseline.scoring import wilson_interval

DEFAULT_HOURLY_RATES = (20.0, 30.0, 40.0)    # illustrative assumptions for the sensitivity table, not findings

ACCURACY_ROWS = (
    ("category_ok", "Category correct"),
    ("actions_ok", "Action set exactly correct"),
    ("escalate_ok", "Escalation decision correct"),
    ("consequential_ok", "Consequential actions correct (refund, replacement, exchange, return label, cancellation, address change)"),
    ("kb_ok", "All required knowledge-base articles identified"),
)


def pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def ratio(correct: int, n: int) -> str:
    """'92.5% (37/40), 95% CI 80.1% to 97.4%'"""
    if n == 0:
        return "n/a (no tickets)"
    low, high = wilson_interval(correct, n)
    return f"{pct(correct / n)} ({correct}/{n}); 95% CI {pct(low)} to {pct(high)}"


def ratio_or_na(x: float, num: int, den: int) -> str:
    return f"{pct(x)} ({num}/{den})" if den else "n/a (none expected or taken)"


def cell(text: str) -> str:
    return text.replace("|", "/")


def render_report(summary: dict, sample: dict, results: list[dict], hourly_rates=DEFAULT_HOURLY_RATES,
                  dataset_version: str | None = None) -> str:
    t, counts = summary["time"], summary["counts"]
    dataset_label = f"dataset version {dataset_version}" if dataset_version else "dataset version in `data/manifest.json`"
    scored = [r for r in results if not r["practice"]]
    first, last = min(r["started_at"] for r in scored)[:10], max(r["started_at"] for r in scored)[:10]
    lines = [
        "# Baseline Report: Manual Ticket Handling", "",
        "Generated by `python -m src.baseline.cli report` from `data/baseline/results.jsonl`. Method: `baseline-protocol.md`.", "",
        "| | |", "|---|---|",
        f"| Dataset | development split, {dataset_label}, {summary['tickets']} scored tickets |",
        f"| Sample | stratified by scenario, seed {sample['seed']}, {len(sample['practice_ids'])} practice tickets excluded |",
        f"| Handler | one person (the project lead) |",
        f"| Sessions | {first} to {last}; {summary['pauses']} pause(s) recorded |", "",
        "## 1. Handling time", "",
        "Handling time runs from the start of the timer to submission of the reply; paused time is excluded.", "",
        "| Statistic | Seconds | Minutes |", "|---|---|---|",
    ]
    for key, name in (("mean", "Mean"), ("median", "Median"), ("p90", "90th percentile"), ("min", "Fastest"), ("max", "Slowest")):
        lines.append(f"| {name} | {t[key]:.0f} | {t[key] / 60:.1f} |")
    lines += [f"| Total ({t['n']} tickets) | {t['total']:.0f} | {t['total'] / 60:.1f} |", "",
              f"Throughput at the mean: {3600 / t['mean']:.1f} tickets per hour.", "",
              "### By difficulty", "", "| Difficulty | Tickets | Mean seconds | Median seconds | Actions exactly correct |",
              "|---|---|---|---|---|"]
    for difficulty, d in summary["by_difficulty"].items():
        lines.append(f"| {difficulty} | {d['n']} | {d['mean']:.0f} | {d['median']:.0f} | {pct(d['actions_ok'])} |")
    learn = summary["learning"]
    lines += ["", f"### Learning effect", "",
              f"Median time over the first {learn['third']} tickets: {learn['first_third_median']:.0f} s; over the last "
              f"{learn['third']}: {learn['last_third_median']:.0f} s (means: {learn['first_third_mean']:.0f} s and "
              f"{learn['last_third_mean']:.0f} s). A large drop would mean early tickets overstate the steady-state time.",
              "", "## 2. Accuracy of manual handling", "",
              "Each rate is shown with the number of tickets and a 95% Wilson confidence interval; at this sample size the interval is wide.", "",
              "| Measure | Rate |", "|---|---|"]
    lines += [f"| {label} | {ratio(counts[key]['correct'], counts[key]['n'])} |" for key, label in ACCURACY_ROWS]
    rel = summary["consequential_relevant"]
    lines += [f"| Consequential actions correct, tickets where such an action was expected or taken | "
              f"{ratio(rel['correct'], rel['n']) if rel['n'] else 'n/a (none)'} |"]
    e = summary["escalation"]
    lines += ["", "### Escalation as a decision", "",
              "| | Label: escalate | Label: do not escalate |", "|---|---|---|",
              f"| Handler escalated | {e['tp']} | {e['fp']} |", f"| Handler did not escalate | {e['fn']} | {e['tn']} |", "",
              f"Precision: {ratio_or_na(e['precision'], e['tp'], e['tp'] + e['fp'])}. "
              f"Recall: {ratio_or_na(e['recall'], e['tp'], e['tp'] + e['fn'])}.", "",
              "### Disagreements with the labels", "",
              "Tickets where at least one of the five measures failed. Each needs a review before it is counted as a handler error "
              "(the label, the knowledge-base article or the policy wording may be the cause).", ""]
    if summary["disagreements"]:
        lines += ["| Ticket | Scenario | Difficulty | Failed measures | Handler: category; actions; escalated | Label: category; actions; escalate | Required articles missed |",
                  "|---|---|---|---|---|---|---|"]
        for r in summary["disagreements"]:
            failed = ", ".join(k.replace("_ok", "") for k in ("category_ok", "actions_ok", "escalate_ok", "consequential_ok", "kb_ok") if not r[k])
            lines.append(
                f"| {r['ticket_id']} | {r['scenario_id']} | {r['difficulty']} | {failed} | "
                f"{r['handled_category']}; {cell(', '.join(r['handled_actions']) or 'none')}; {'yes' if r['handled_escalate'] else 'no'} | "
                f"{r['category']}; {cell(', '.join(r['expected_actions']) or 'none')}; {'yes' if r['expected_escalate'] else 'no'} | "
                f"{', '.join(r['missing_kb']) or '-'} |")
    else:
        lines.append("None.")
    lines += ["", "## 3. Cost per ticket (sensitivity)", "",
              "Local compute costs nothing, so the business case compares labour time. The hourly rates below are "
              "assumptions chosen to show sensitivity; the rate that applies to a real support team is an input, not a result.", "",
              "| Assumed fully loaded labour cost per hour | Cost per ticket at the mean time | Cost per 1,000 tickets |", "|---|---|---|"]
    lines += [f"| ${r:,.2f} | ${t['mean'] / 3600 * r:,.2f} | ${t['mean'] / 3600 * r * 1000:,.0f} |" for r in hourly_rates]
    lines += ["", "## 4. Limitations", "",
              "- One handler, who is also the author of the project and designed the dataset. Familiarity with the ticket types "
              "probably makes these times faster than a new support agent's, so the baseline may understate real handling time.",
              "- Record lookups run in a terminal tool and are faster than switching between real order, payment and knowledge-base systems.",
              "- Tickets are synthetic and short; real tickets contain more noise, attachments and history.",
              "- Sessions were free of interruptions apart from recorded pauses, unlike a live queue.",
              f"- {summary['tickets']} tickets is a small sample: use the median and the spread, and do not read differences of a few percent as real.",
              "- Accuracy is measured against generated labels, which follow the project's own policy and priority rubric.", ""]
    return "\n".join(lines)